name: ci.kaitai.io

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
          submodules: true
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - name: Deploy
        env:
          BOT_SSH_KEY: ${{secrets.BOT_SSH_KEY}}
        run: |
          ./push_artifacts/git_config_kaitai_bot
          ./push_artifacts/publish \
            -o kaitai-io \
            -r ci-kaitai-io.github.io \
            -m "Build results of ${GITHUB_REF#refs/heads/*} $GITHUB_REPOSITORY@$GITHUB_SHA" \
            -- \
            --exclude=.git \
            --exclude=CNAME \
            --exclude=favicon.ico \
            --exclude=favicon.ico.license \
            dist/
