name: ci.kaitai.io

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - name: Deploy
        env:
          BOT_SSH_KEY: ${{secrets.BOT_SSH_KEY}}
        run: |
          ./push_artifacts/git_config_kaitai_bot
          ./push_artifacts/publish \
            -o kaitai-io \
            -r ci-kaitai-io.github.io \
            -m "Build results of ${GITHUB_REF#refs/heads/*} $GITHUB_REPOSITORY@$GITHUB_SHA" \
            -- \
            --exclude=.git \
            --exclude=CNAME \
            --exclude=favicon.ico \
            --exclude=favicon.ico.license \
            dist/
